language: julia
julia:
  - 1.1

codecov: true
coveralls: false

before_install:
  - brew install lightgbm

os:
  - osx

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'